"""One-off sender for the reviewed tutor-outreach drafts in
C:\\Users\\ssjag\\OneDrive\\Ace11Plus\\Outreach\\drafts\\*.txt, via the same
Resend account/domain (support@ace11plus.org) the app already uses for
transactional email (src/lib/resend.ts).

Sends exactly the drafts generated by generate_tutor_outreach.py, unmodified,
one Resend API call per draft. Requires explicit human approval per draft --
this script does not decide what to send, only sends what's already on disk
and been reviewed.

Usage:
  RESEND_API_KEY=... python scripts/send_tutor_outreach.py [--dry-run] [--only CODE ...]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import requests

from reel_common import get_env, load_env_files, logger

DRAFTS_DIR = Path(r"C:\Users\ssjag\OneDrive\Ace11Plus\Outreach\drafts")
FROM_ADDRESS = "Ace 11+ <support@ace11plus.org>"


def parse_draft(path: Path) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    to_match = re.match(r"To:\s*(.+)\r?\n", text)
    if not to_match:
        raise ValueError(f"{path}: missing 'To:' line")
    to_addr = to_match.group(1).strip()
    rest = text[to_match.end():]
    subject_match = re.match(r"Subject:\s*(.+)\r?\n\r?\n", rest)
    if not subject_match:
        raise ValueError(f"{path}: missing 'Subject:' line")
    subject = subject_match.group(1).strip()
    body = rest[subject_match.end():]
    return to_addr, subject, body


def send_via_resend(api_key: str, to_addr: str, subject: str, body: str) -> None:
    resp = requests.post(
        "https://api.resend.com/emails",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "from": FROM_ADDRESS,
            "to": [to_addr],
            "subject": subject,
            "text": body,
        },
        timeout=30,
    )
    resp.raise_for_status()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Send reviewed tutor outreach drafts via Resend.")
    parser.add_argument("--dry-run", action="store_true", help="Parse and print without sending.")
    parser.add_argument("--only", nargs="*", help="Only send these draft codes (filename stems).")
    return parser.parse_args()


def main() -> int:
    load_env_files()
    args = parse_args()

    api_key = get_env("RESEND_API_KEY", required=not args.dry_run) if not args.dry_run else get_env("RESEND_API_KEY")

    drafts = sorted(p for p in DRAFTS_DIR.glob("*.txt"))
    if args.only:
        wanted = set(args.only)
        drafts = [p for p in drafts if p.stem in wanted]

    if not drafts:
        logger.error("No draft files found in %s", DRAFTS_DIR)
        return 1

    sent = 0
    for path in drafts:
        to_addr, subject, body = parse_draft(path)
        if args.dry_run:
            logger.info("[DRY RUN] Would send %s -> %s (subject: %s)", path.stem, to_addr, subject)
            continue
        try:
            send_via_resend(api_key, to_addr, subject, body)
            logger.info("Sent %s -> %s", path.stem, to_addr)
            sent += 1
        except Exception as exc:  # noqa: BLE001
            logger.error("Failed to send %s -> %s: %s", path.stem, to_addr, exc)

    logger.info("SUMMARY: %s/%s email(s) sent.", sent, len(drafts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
